#ifndef VERSION_H
#define VERSION_H

#include <string>

namespace HCMFFmpegMedia {
static std::string g_version_str;

#define FFMPEG_MEDIA_VERSION_MAJOR 0
#define FFMPEG_MEDIA_VERSION_MINOR 0
#define FFMPEG_MEDIA_VERSION_REVISION 3

#define FFMPEG_MEDIA_VERSION_STATUS "HCMFFmpegMedia"


#define FFMPEG_MEDIA_AUX_STR_EXP(__A) #__A
#define FFMPEG_MEDIA_AUX_STR(__A) FFMPEG_MEDIA_AUX_STR_EXP(__A)
#define FFMPEG_MEDIA_VERSION_STR FFMPEG_MEDIA_AUX_STR(FFMPEG_MEDIA_VERSION_MAJOR)"." \
    FFMPEG_MEDIA_AUX_STR(FFMPEG_MEDIA_VERSION_MINOR)"." \
    FFMPEG_MEDIA_AUX_STR(FFMPEG_MEDIA_VERSION_REVISION)" " \
    FFMPEG_MEDIA_VERSION_STATUS


// 宽字符表示
#define FFMPEG_MEDIA_AUX_WSTR_EXP(__A) L## #__A
#define FFMPEG_MEDIA_AUX_WSTR(__A) FFMPEG_MEDIA_AUX_WSTR_EXP(__A)
#define FFMPEG_MEDIA_VERSION_WSTR FFMPEG_MEDIA_AUX_WSTR(FFMPEG_MEDIA_VERSION_MAJOR)"." \
    FFMPEG_MEDIA_AUX_WSTR(FFMPEG_MEDIA_VERSION_MINOR)"." \
    FFMPEG_MEDIA_AUX_WSTR(FFMPEG_MEDIA_VERSION_REVISION)" " \
    FFMPEG_MEDIA_VERSION_STATUS


std::string fm_get_version(){
    g_version_str = FFMPEG_MEDIA_VERSION_STR;
    return g_version_str;
}

}

#endif // VERSION_H
